### ISSUE TITLE
com.intellij.psi.impl.compiled.ClsMethodImpl cannot be cast to org.jetbrains.kotlin.psi.KtFunction

### ISSUE THREAD

**Issue by javatlacati** [trubitsyn/VisibleForTesting#51]
Details
---

deleted `<String, *>` from the code

```
 private fun decode(input:String):String {
    return Stream.of<String>(*input.replace(("\\\\[u]([\\da-f]{4})").toRegex(), "$1 ").split((" ").toRegex()).dropLastWhile({ it.isEmpty() }).toTypedArray()).map<String>(
      { codePoint-> ((Integer.valueOf(codePoint, 16).toInt()).toChar()).toString() }
    ).collect<String, *>(Collectors.joining(""))
  }
```

that was inside a kotlin test class.

Details
---

> om.intellij.psi.impl.compiled.ClsMethodImpl cannot be cast to org.jetbrains.kotlin.psi.KtFunction
java.lang.ClassCastException: com.intellij.psi.impl.compiled.ClsMethodImpl cannot be cast to org.jetbrains.kotlin.psi.KtFunction
	at io.github.trubitsyn.visiblefortesting.intention.AnnotateKtFunctionFromTestIntention.isApplicableTo(AnnotateKtFunctionFromTestIntention.kt:50)
	at io.github.trubitsyn.visiblefortesting.intention.AnnotateKtFunctionFromTestIntention.isApplicableTo(AnnotateKtFunctionFromTestIntention.kt:33)
	at org.jetbrains.kotlin.idea.intentions.SelfTargetingIntention.getTarget(SelfTargetingIntention.kt:76)
	at org.jetbrains.kotlin.idea.intentions.SelfTargetingIntention.isAvailable(SelfTargetingIntention.kt:92)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$2(ShowIntentionsPass.java:340)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:339)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:269)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:245)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by trubitsyn** [comment]
Hello, @javatlacati! Thank you for a detailed report. I'll try to fix this asap.

**Comment by trubitsyn** [comment]
@javatlacati version 1.3.1 with this fix included has just been released.
